### ISSUE TITLE
Node V4 Support

### ISSUE THREAD

**Issue by rydn** [yahoo/monitr#31]
Compilation on Node v4 fails with: 

```
> monitr@0.0.15 install /home/ryan/Dev/Projects/monitr
> node-gyp rebuild

make: Entering directory '/home/ryan/Dev/Projects/monitr/build'
  CXX(target) Release/obj.target/monitor/src/monitor.o
In file included from ../src/monitor.cc:15:0:
/home/ryan/.node-gyp/4.0.0/include/node/node_internals.h:5:18: fatal error: util.h: No such file or directory
compilation terminated.
monitor.target.mk:94: recipe for target 'Release/obj.target/monitor/src/monitor.o' failed
make: *** [Release/obj.target/monitor/src/monitor.o] Error 1
make: Leaving directory '/home/ryan/Dev/Projects/monitr/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ryan/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.1.6-201.fc22.x86_64
gyp ERR! command "/home/ryan/.nvm/versions/node/v4.0.0/bin/node" "/home/ryan/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ryan/Dev/Projects/monitr
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 
```

**Comment by rydn** [comment]
Same issue appears with any version greater than  io.js 2.4.0

**Comment by evantorrie** [comment]
Thanks for the report.  I'm taking a look at this today - so far, we have been sitting still on nodejs v0.12, but yes, it's time to move.

**Comment by evantorrie** [comment]
Addressed in PR #32
Waiting for code review and any subsequent changes.

**Comment by evantorrie** [comment]
OK, this should now work with nodejs-4.0.0 as of monitr-0.1.0.  Let me know if it doesn't work for you.

**Comment by rydn** [comment]
works great.
